spring:
  application:
    name: serviceone
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.23.72.193:3306/yundesk?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: usernameforU
    password: mYpassword!4
env: dev3
